### ISSUE TITLE
UnsupportedOperationException on container shutdown

### ISSUE THREAD

**Issue by lefou** [domino-osgi/domino#17]
Looks like some wrapped Java Collection does not support the remove operation.

java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
Scala 2.10.6
Domino 1.1.1

```
g! stop 0
g! java.lang.UnsupportedOperationException: remove
        at scala.collection.convert.Wrappers$MapWrapper$$anon$1$$anon$5.remove(Wrappers.scala:206)
        at java.util.AbstractCollection.clear(Unknown Source)
        at java.util.AbstractMap.clear(Unknown Source)
        at org.apache.ftpserver.impl.DefaultFtpServerContext.dispose(DefaultFtpServerContext.java:198)
        at org.apache.ftpserver.impl.DefaultFtpServer.stop(DefaultFtpServer.java:126)
        at de.woq.XXX.sib.ftpserver.internal.FtpServerLifecycle.destroy(FtpServerLifecycle.java:87)
        at de.woq.XXX.sib.ftpserver.internal.FTPServerActivator$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(FTPServerActivator.scala:103)
        at domino.capsule.CapsuleConvenience$$anon$2.stop(CapsuleConvenience.scala:38)
        at domino.capsule.DefaultCapsuleScope$$anonfun$stop$1.apply(DefaultCapsuleScope.scala:11)
        at domino.capsule.DefaultCapsuleScope$$anonfun$stop$1.apply(DefaultCapsuleScope.scala:11)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
        at domino.capsule.DefaultCapsuleScope.stop(DefaultCapsuleScope.scala:11)
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1$$anonfun$apply$1.apply(ServiceWatching.scala:96)
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1$$anonfun$apply$1.apply(ServiceWatching.scala:93)
        at scala.Option.foreach(Option.scala:236)
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1.apply(ServiceWatching.scala:93)
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1.apply(ServiceWatching.scala:80)
        at domino.service_watching.ServiceWatcherCapsule$$anon$1.removedService(ServiceWatcherCapsule.scala:46)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:956)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:864)
        at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:341)
        at org.osgi.util.tracker.ServiceTracker.close(ServiceTracker.java:375)
        at domino.service_watching.ServiceWatcherCapsule.stop(ServiceWatcherCapsule.scala:56)
        at domino.capsule.DefaultCapsuleScope$$anonfun$stop$1.apply(DefaultCapsuleScope.scala:11)
        at domino.capsule.DefaultCapsuleScope$$anonfun$stop$1.apply(DefaultCapsuleScope.scala:11)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
        at domino.capsule.DefaultCapsuleScope.stop(DefaultCapsuleScope.scala:11)
        at domino.configuration_watching.ConfigurationWatcherCapsule$$anonfun$stop$1.apply(ConfigurationWatcherCapsule.scala:74)
        at domino.configuration_watching.ConfigurationWatcherCapsule$$anonfun$stop$1.apply(ConfigurationWatcherCapsule.scala:74)
        at scala.Option.foreach(Option.scala:236)
        at domino.configuration_watching.ConfigurationWatcherCapsule.stop(ConfigurationWatcherCapsule.scala:74)
        at domino.capsule.DefaultCapsuleScope$$anonfun$stop$1.apply(DefaultCapsuleScope.scala:11)
        at domino.capsule.DefaultCapsuleScope$$anonfun$stop$1.apply(DefaultCapsuleScope.scala:11)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
        at domino.capsule.DefaultCapsuleScope.stop(DefaultCapsuleScope.scala:11)
        at domino.OsgiContext$$anonfun$stop$1.apply(OsgiContext.scala:67)
        at domino.OsgiContext$$anonfun$stop$1.apply(OsgiContext.scala:66)
        at scala.Option.foreach(Option.scala:236)
        at domino.OsgiContext$class.stop(OsgiContext.scala:66)
        at domino.DominoActivator.stop(DominoActivator.scala:66)
        at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:719)
        at org.apache.felix.framework.Felix.stopBundle(Felix.java:2604)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1383)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Unknown Source)
java.lang.UnsupportedOperationException: remove
        at scala.collection.convert.Wrappers$MapWrapper$$anon$1$$anon$5.remove(Wrappers.scala:206)
        at java.util.AbstractCollection.clear(Unknown Source)
        at java.util.AbstractMap.clear(Unknown Source)
        at org.apache.ftpserver.impl.DefaultFtpServerContext.dispose(DefaultFtpServerContext.java:198)
        at org.apache.ftpserver.impl.DefaultFtpServer.stop(DefaultFtpServer.java:126)
        at de.woq.XXX.sib.ftpserver.internal.FtpServerLifecycle.destroy(FtpServerLifecycle.java:87)
        at de.woq.XXX.sib.ftpserver.internal.FTPServerActivator$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(FTPServerActivator.scala:103)
        at domino.capsule.CapsuleConvenience$$anon$2.stop(CapsuleConvenience.scala:38)
        at domino.capsule.DefaultCapsuleScope$$anonfun$stop$1.apply(DefaultCapsuleScope.scala:11)
        at domino.capsule.DefaultCapsuleScope$$anonfun$stop$1.apply(DefaultCapsuleScope.scala:11)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
        at domino.capsule.DefaultCapsuleScope.stop(DefaultCapsuleScope.scala:11)
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1$$anonfun$apply$1.apply(ServiceWatching.scala:96)
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1$$anonfun$apply$1.apply(ServiceWatching.scala:93)
        at scala.Option.foreach(Option.scala:236)
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1.apply(ServiceWatching.scala:93)
        at domino.service_watching.ServiceWatching$$anonfun$whenAdvancedServicePresent$1.apply(ServiceWatching.scala:80)
        at domino.service_watching.ServiceWatcherCapsule$$anon$1.removedService(ServiceWatcherCapsule.scala:46)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:956)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:864)
        at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:341)
        at org.osgi.util.tracker.ServiceTracker.close(ServiceTracker.java:375)
        at domino.service_watching.ServiceWatcherCapsule.stop(ServiceWatcherCapsule.scala:56)
        at domino.capsule.DefaultCapsuleScope$$anonfun$stop$1.apply(DefaultCapsuleScope.scala:11)
        at domino.capsule.DefaultCapsuleScope$$anonfun$stop$1.apply(DefaultCapsuleScope.scala:11)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
        at domino.capsule.DefaultCapsuleScope.stop(DefaultCapsuleScope.scala:11)
        at domino.configuration_watching.ConfigurationWatcherCapsule$$anonfun$stop$1.apply(ConfigurationWatcherCapsule.scala:74)
        at domino.configuration_watching.ConfigurationWatcherCapsule$$anonfun$stop$1.apply(ConfigurationWatcherCapsule.scala:74)
        at scala.Option.foreach(Option.scala:236)
        at domino.configuration_watching.ConfigurationWatcherCapsule.stop(ConfigurationWatcherCapsule.scala:74)
        at domino.capsule.DefaultCapsuleScope$$anonfun$stop$1.apply(DefaultCapsuleScope.scala:11)
        at domino.capsule.DefaultCapsuleScope$$anonfun$stop$1.apply(DefaultCapsuleScope.scala:11)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
        at domino.capsule.DefaultCapsuleScope.stop(DefaultCapsuleScope.scala:11)
        at domino.OsgiContext$$anonfun$stop$1.apply(OsgiContext.scala:67)
        at domino.OsgiContext$$anonfun$stop$1.apply(OsgiContext.scala:66)
        at scala.Option.foreach(Option.scala:236)
        at domino.OsgiContext$class.stop(OsgiContext.scala:66)
        at domino.DominoActivator.stop(DominoActivator.scala:66)
        at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:719)
        at org.apache.felix.framework.Felix.stopBundle(Felix.java:2604)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1383)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Unknown Source)
ERROR: Bundle de.woq.XXX.sib.ftpserver [127] Error stopping bundle. (java.lang.UnsupportedOperationException: remove)
ERROR: Bundle de.woq.XXX.sib.ftpserver [127] Error stopping file:/home/lefou/work/woq/XXX-sib-2.0/assembly/de.woq.XXX.sib.blended.shop/target/de.woq.XXX.blended.shop-2.0.12-SNAPSHOT/profiles/XXX-shop/2.0.12-SNAPSHOT/bundles/de.woq.XXX.sib.ftpserver-2.0-SNAPSHOT.jar (org.osgi.framework.BundleException: Activator stop error in bundle de.woq.XXX.sib.ftpserver [127].)
```

**Comment by lefou** [comment]
Seems unrelated to domino.
